CrystalReportsInASP.NETWebApp/Models/Department.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CrystalReportsInASP.NETWebApp.Models
{
    public class Department
    {
        public long DepartmentID { get; set; }
        public string DepartmentName { get; set; }

    }
}

CrystalReportsInASP.NETWebApp/Models/EmployeeInfoEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CrystalReportsInASP.NETWebApp.Models
{
    public class EmployeeInfoEntity
    {
        public long EmployeeID { get; set; }
        public string EmployeeName { get; set; } = string.Empty;
        public string Department { get; set; } = string.Empty;
        public string MailID { get; set; } = string.Empty;
        public DateTime DOJ { get; set; }

    }
}

CrystalReportsInASP.NETWebApp/Models/ReportParams.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CrystalReportsInASP.NETWebApp.Models
{
    public class ReportParams<T>
    {
        public string RptFileName { get; set; }
        public string ReportTitle { get; set; }
        public List<T> DataSource { get; set; }
        public bool IsPassParamToCr { get; set; }
    }
}

CrystalReportsInASP.NETWebApp/Controllers/DepartmentController.cs
using CrystalReportsInASP.NETWebApp.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace CrystalReportsInASP.NETWebApp.Controllers
{
    public class DepartmentController : Controller
    {
        // GET: Department
        public ActionResult DepartmentReport()
        {
            return View();
        }

        public void GenerateDepartmentReport()
        {
            ReportParams<Department> objReportParams = new ReportParams<Department>();

            objReportParams.DataSource = GetAllEmployee();
            objReportParams.ReportTitle = "Department Info Report";
            objReportParams.RptFileName = "DepartmentReport.rpt";
            this.HttpContext.Session["ReportType"] = "DepartmentReport";
            this.HttpContext.Session["ReportParam"] = objReportParams;
        }

        public List<Department> GetAllEmployee()
        {
            string constr = ConfigurationManager.ConnectionStrings["SqlConnectionString"].ConnectionString;
            DataTable dt = new DataTable();
            string sql = "SELECT * FROM  Departments";
            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand(sql, con);
            SqlDataAdapter adpt = new SqlDataAdapter(cmd);
            adpt.Fill(dt);

            var list = ConvertDataTableToList<Department>(dt);

            return list;
        }

        private static List<T> ConvertDataTableToList<T>(DataTable dt)
        {

            List<T> data = new List<T>();
            foreach (DataRow row in dt.Rows)
            {
                T item = GetItem<T>(row);
                data.Add(item);
            }
            return data;
        }

        private static T GetItem<T>(DataRow dr)
        {
            Type temp = typeof(T);
            T obj = Activator.CreateInstance<T>();

            foreach (DataColumn column in dr.Table.Columns)
            {
                foreach (PropertyInfo pro in temp.GetProperties())
                {
                    if (pro.Name == column.ColumnName)
                        pro.SetValue(obj, dr[column.ColumnName], null);
                    else
                        continue;

                }

            }

            return obj;
        }

    }
}

CrystalReportsInASP.NETWebApp/Controllers/EmployeeController.cs
using CrystalReportsInASP.NETWebApp.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace CrystalReportsInASP.NETWebApp.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult EmployeeReport()
        {
            return View();
        }

        public void GenerateEmployeeReport()
        {
            ReportParams<EmployeeInfoEntity> objReportParams = new ReportParams<EmployeeInfoEntity>();

            objReportParams.DataSource = GetAllEmployee();
            objReportParams.ReportTitle = "Employee Info Report";
            objReportParams.RptFileName = "EmployeeInfReport.rpt";
            this.HttpContext.Session["ReportType"] = "EmployeeInfoReport";
            this.HttpContext.Session["ReportParam"] = objReportParams;
        }

        public List<EmployeeInfoEntity> GetAllEmployee()
        {
            string constr = ConfigurationManager.ConnectionStrings["SqlConnectionString"].ConnectionString;
            DataTable dt = new DataTable();
            string sql = "SELECT * FROM  Employees";
            SqlConnection con = new SqlConnection(constr);
            SqlCommand cmd = new SqlCommand(sql, con);
            SqlDataAdapter adpt = new SqlDataAdapter(cmd);
            adpt.Fill(dt);

            var list = ConvertDataTableToList<EmployeeInfoEntity>(dt);

            return list;
        }

        private static List<T> ConvertDataTableToList<T>(DataTable dt)
        {

            List<T> data = new List<T>();
            foreach(DataRow row in dt.Rows)
            {
                T item = GetItem<T>(row);
                data.Add(item);
            }
            return data;
        }

        private static T GetItem<T>(DataRow dr)
        {
            Type temp = typeof(T);
            T obj = Activator.CreateInstance<T>();

            foreach (DataColumn column in dr.Table.Columns)
            {
                foreach (PropertyInfo pro in temp.GetProperties())
                {
                    if (pro.Name == column.ColumnName)
                        pro.SetValue(obj, dr[column.ColumnName], null);
                    else
                        continue;

                }

            }

            return obj;
        }
    }
}

CrystalReportsInASP.NETWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CrystalReportsInASP.NETWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CrystalReportsInASP.NETWebApp/Views/Department/DepartmentReport.cshtml

@{
    ViewBag.Title = "DepartmentReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/DepartmentReport/DepartmentReport.js"></script>


<div class="jumbotron">
    Department Report
</div>

<div>
    <button class="btn btn-info" id="btnLoadReport">
        Load Report
    </button>

</div>



CrystalReportsInASP.NETWebApp/Views/Employee/EmployeeReport.cshtml

@{
    ViewBag.Title = "EmployeeReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
<script src="~/Scripts/EmployeeReport/EmployeeReport.js"></script>

<div class="jumbotron">
    Employee Report
</div>

<div>
    <button class="btn btn-info" id="btnLoadReport">
        Load Report
    </button>

</div>



CrystalReportsInASP.NETWebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

CrystalReportsInASP.NETWebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CrystalReportsInASP.NETWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div class="jumbotron">
    <h1>Crystal report Designing </h1>
     
</div>

<div class="row">
   
    
</div>

CrystalReportsInASP.NETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
<script src="~/Scripts/jquery-3.4.1.js"></script>

    <style>
    .navbar-inverse {
    background-color: #002147 !important;
    border-color: #002147 !important;
    }

    .navbar-inverse .navbar-brand {
    color: #fff !important;
    }

    .navbar-inverse .navbar-nav > li > a {
    color: #9d9d9d !important;
    }

    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("CRYSTAL REPORTS", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li> 
                    <li>@Html.ActionLink("Employee Report", "EmployeeReport", "Employee")</li>
                    <li>@Html.ActionLink("Department Report", "DepartmentReport", "Department")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Crystal Reports</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>